### ISSUE TITLE
Add list of interviews in applicant and positions

### ISSUE THREAD

**Issue by likeabowx** [AY2122S2-CS2103-W17-4/tp#127]
It will be useful to keep track of the relevant interviews under `Applicant` and `Position`, such as for cascading when deleting and to check if an applicant already has an interview at the given time.

I'm thinking to just keep an ArrayList<Interview> attribute in `Applicant` and `Position`, with the method `addRelatedInterview()` to append to the relevant list whenever an interview is added. Will that cause problems later?

**Comment by YiHern-Lee** [comment]
@likeabowx I do not think its necessary to keep track of Interviews in Applicant and Position. In fact, it may lead to excessive coupling between the different Model classes. I think the association of these classes can be checked by scanning through the lists in the main model manager. 

Since the model classes are also immutable, it may be extremely inefficient when editing means creating a whole new object and updating the main list to hold the new object instead. You'll have to comb through all Applicants and Positions (and their individual nested lists) to find the references to update.

**Comment by likeabowx** [comment]
I agree with the point brought up regarding the inefficiency when editing if we do keep a list under applicants and positions. In that case, when deleting interviews, I think I will just scan through the applicants and positions lists to find the corresponding item to delete. 

@goalfix When adding interview, we need to check if the applicant already has an interview at that time. In that case, we will scan through the interviews list to find the corresponding applicant and check the time?

**Comment by likeabowx** [comment]
I have added methods `isInterviewForApplicant()` and `isInterviewForPosition()` under `Interview` to help check when looping through the list of interviews. I will close this issue now.
